# Default values for compreface-kubernetes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

postgres:
  repository: postgres
  pullPolicy: Always
  tag: 11.5
  db_name: frs
  db_port: 5432
  db_password: postgres
  db_user: postgres
  name: cf-db-data
  maxBodySize: "5000K"
  # resources:
  #     requests:
  #       cpu: "0.015"
  #       memory: 100Mi
  #     limits:
  #       memory: 200Mi
  #       cpu: "0.03"
  # storageClass: your-storage-class
  # storageSize: 100Mi

core:
  repository: exadel/compreface-core
  pullPolicy: Always
  tag: 0.5.1
  port: 3000
  replicas: 1
  name: cf-core
  # resources:
  #     requests:
  #       cpu: "0.015"
  #       memory: 100Mi
  #     limits:
  #       memory: 200Mi
  #       cpu: "0.03"
  #       nvidia.com/gpu: 1
  ## Tolerations can be made specifically for core to allow use on GPU tainted nodes
  # tolerations:
  # - key: nvidia.com/gpu
  #   operator: Exists



api:
  repository: exadel/compreface-api
  pullPolicy: Always
  tag: 0.5.1
  port: 8080
  replicas: 1
  name: cf-api
  # resources:
  #     requests:
  #       cpu: "0.015"
  #       memory: 100Mi
  #     limits:
  #       memory: 200Mi
  #       cpu: "0.03"

admin:
  repository: exadel/compreface-admin
  pullPolicy: Always
  tag: 0.5.1
  port: 8080
  replicas: 1
  name: cf-admin # resources:
  #     requests:
  #       cpu: "0.015"
  #       memory: 100Mi
  #     limits:
  #       memory: 200Mi
  #       cpu: "0.03"



fe:
  repository: exadel/compreface-fe
  pullPolicy: Always
  tag: 0.5.1
  port: 80
  replicas: 1
  name: cf-fe
  # resources:
  #     requests:
  #       cpu: "0.015"
  #       memory: 100Mi
  #     limits:
  #       memory: 200Mi
  #       cpu: "0.03"

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/issuer: "adcs-cluster-issuer" #use specific name of issuer
      cert-manager.io/issuer-kind: "ClusterAdcsIssuer" #or AdcsClusterIssuer
      cert-manager.io/issuer-group: "adcs.certmanager.csf.nokia.com"
      cert-manager.io/common-name: "$SITECODE-compreface.macsc.net.au"
      cert-manager.io/subject-organizations: "Southern Cross Austereo"
      cert-manager.io/subject-organizationalunits: "Technology Services"
      cert-manager.io/subject-countries: "AU"
      cert-manager.io/subject-localities: "$SITE"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    hosts:
    - "$SITECODE-compreface.macsc.net.au"
    - "compreface.macsc.net.au"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "compreface"

podAnnotations: {}

podSecurityContext: {} # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
  - host: chart-example.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
