apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ print .Release.Name "-db-data" | lower | nospace }}
  name: {{ print .Release.Name "-" .Values.postgres.name | lower | nospace }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- if hasKey .Values.postgres "storageClass" }}
  storageClassName: {{ .Values.postgres.storageClass }}
  {{- end }}  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize | default "100Mi" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ print .Release.Name "-db" | lower | nospace }}
  name: {{ print .Release.Name "-" .Values.postgres.name | lower | nospace }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ print .Release.Name "-db" | lower | nospace }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ print .Release.Name "-db" | lower | nospace }}
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db_name }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.db_password }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.db_user }}
            {{-if hasKey .Values.postgres "env"-}}
              {{- range $env := .Values.postgres.env }}
            - name: {{ $env.name | quote }}
              value: {{- if and (eq (typeOf $env.value) "bool") }} {{ $env.value }} {{- else }} {{ $env.value | quote }} {{- end }}
              {{- end}}
            {{- end }}
          image: {{ .Values.postgres.repository }}:{{ .Values.postgres.tag }}
          {{- if hasKey .Values.postgres "resources" }}
          resources:
          {{- if hasKey .Values.postgres.resources "limits" }}
          limits:
            memory: {{ .Values.postgres.resources.limits.memory | quote }}
            cpu: {{ .Values.postgres.resources.limits.cpu | quote }}
          {{- end }}
          {{- if hasKey .Values.postgres.resources "requests" }}
          requests:
            memory: {{ .Values.postgres.resources.requests.memory | quote }}
            cpu: {{ .Values.postgres.resources.requests.cpu | quote }}
          {{- end }}
          {{- end }}
          name: cf-db
          ports:
          - containerPort: {{ .Values.postgres.db_port }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: {{ print .Release.Name "-" .Values.postgres.name | lower | nospace }}
              subPath: postgres
      restartPolicy: Always
      {{- if hasKey .Values.postgres "imagePullSecrets" }}
      imagePullSecrets:
        {{- range .Values.postgres.imagePullSecrets }}
      - name: {{ . }}
        {{- end }}
      {{- end }}

      volumes:
        - name: {{ print .Release.Name "-" .Values.postgres.name | lower | nospace }}
          persistentVolumeClaim:
            claimName: {{ print .Release.Name "-" .Values.postgres.name | lower | nospace }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ print .Release.Name "-compreface-postgres-db" | lower | nospace }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
      app: {{ print .Release.Name "-db" | lower | nospace }}
  ports:
  - port: {{ .Values.postgres.db_port }}
