apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ print .Release.Name "-core" }}
  name: {{ print .Release.Name "-" .Values.core.name | lower | nospace }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.core.replicas }}
  selector:
    matchLabels:
      app: {{ print .Release.Name "-core" }}
  template:
    metadata:
      labels:
        app: {{ print .Release.Name "-core" }}
    spec:
{{- if .Values.core.tolerations }}
      tolerations:
  {{- range $toleration := .Values.core.tolerations }}
        - key: {{ $toleration.key | quote }}
          operator: {{ $toleration.operator | quote }}
    {{- if $toleration.value }}
          value: {{ $toleration.value | quote }}
    {{- end }}
    {{- if $toleration.effect }}
          effect: {{ $toleration.effect | quote }}
    {{- end }}
    {{- if $toleration.tolerationSeconds }}
          tolerationSeconds: {{ $toleration.tolerationSeconds }}
    {{- end }}
  {{- end }}
{{- end }}
      containers:
        - env:
            - name: ML_PORT
              value: "{{ .Values.core.port }}"
            {{-if hasKey .Values.core "env"-}}
              {{- range $env := .Values.core.env }}
            - name: {{ $env.name | quote }}
              value: {{- if and (eq (typeOf $env.value) "bool") }} {{ $env.value }} {{- else }} {{ $env.value | quote }} {{- end }}
              {{- end}}
            {{- end }}
          image: {{ .Values.core.repository }}:{{ .Values.core.tag }}
          {{- if hasKey .Values.core "resources" }}
          resources:
          {{- if hasKey .Values.core.resources "limits" }}
          limits:
            memory: {{ .Values.core.resources.limits.memory | quote }}
            cpu: {{ .Values.core.resources.limits.cpu | quote }}
            {{- if .Values.core.resources.limits.gpu }}
            nvidia.com/gpu: {{ .Values.core.resources.limits.gpu | quote }}
            {{- end }}
          {{- end }}
          {{- if hasKey .Values.core.resources "requests" }}
          requests:
            memory: {{ .Values.core.resources.requests.memory | quote }}
            cpu: {{ .Values.core.resources.requests.cpu | quote }}
          {{- end }}
          {{- end }}
          ports:
          - containerPort: {{ .Values.core.port }}
          name: {{ .Values.core.name }}
      restartPolicy: Always
      {{- if hasKey .Values.core "imagePullSecrets" }}
      imagePullSecrets:
        {{- range .Values.core.imagePullSecrets }}
      - name: {{ . }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ print .Release.Name "-compreface-core" | lower | nospace }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
      app: {{ print .Release.Name "-core" }}
  ports:
  - port: {{ .Values.core.port }}
