apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ print .Release.Name "-core" }}
  name: {{ print .Release.Name "-" .Values.core.name | lower | nospace }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.core.replicas }}
  selector:
    matchLabels:
      app: {{ print .Release.Name "-core" }}
  template:
    metadata:
      labels:
        app: {{ print .Release.Name "-core" }}
    spec:
{{- if .Values.core.tolerations }}
      tolerations:
  {{- range $toleration := .Values.core.tolerations }}
        - key: {{ $toleration.key | quote }}
          operator: {{ $toleration.operator | quote }}
    {{- if $toleration.value }}
          value: {{ $toleration.value | quote }}
    {{- end }}
    {{- if $toleration.effect }}
          effect: {{ $toleration.effect | quote }}
    {{- end }}
    {{- if $toleration.tolerationSeconds }}
          tolerationSeconds: {{ $toleration.tolerationSeconds }}
    {{- end }}
  {{- end }}
{{- end }}
      containers:
        - env:
            - name: ML_PORT
              value: "{{ .Values.core.port }}"
          image: {{ .Values.core.repository }}:{{ .Values.core.tag }}
          resources:
          {{- if .Values.core.resources.limits }}
          limits:
            memory: {{ default "256Mi" .Values.core.resources.limits.memory | quote }}
            cpu: {{ default "0.02" .Values.core.resources.limits.cpu | quote }}
            {{- if .Values.core.resources.limits.gpu }}
            nvidia.com/gpu: {{ .Values.core.resources.limits.gpu | quote }}
            {{- end }}
          {{- end }}
          {{- if .Values.core.resources.requests }}
          requests:
            memory: {{ default "125Mi" .Values.core.resources.requests.memory | quote }}
            cpu: {{ default "0.015" .Values.core.resources.requests.cpu | quote }}
          {{- end }}
          ports:
          - containerPort: {{ .Values.core.port }}
          name: {{ .Values.core.name }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {{ print .Release.Name "-compreface-core" | lower | nospace }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
      app: {{ print .Release.Name "-core" }}
  ports:
  - port: {{ .Values.core.port }}
