apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ print .Release.Name "-api" }}
  name: {{ print .Release.Name "-" .Values.api.name | lower | nospace }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ print .Release.Name "-api" }}
  template:
    metadata:
      labels:
        app: {{ print .Release.Name "-api" }}
    spec:
      containers:
        - env:
            - name: API_JAVA_OPTS
              value: '-Xmx8g'
            - name: POSTGRES_PASSWORD
              value: '{{ .Values.postgres.db_password }}'
            - name: POSTGRES_URL
              value: 'jdbc:postgresql://{{ print .Release.Name "-compreface-postgres-db" | lower | nospace }}:{{ .Values.postgres.db_port }}/{{ .Values.postgres.db_name }}'
            - name: POSTGRES_USER
              value: '{{ .Values.postgres.db_user }}'
            - name: SAVE_IMAGES_TO_DB
              value: 'true'
            - name: SPRING_PROFILES_ACTIVE
              value: 'dev'
            {{- if hasKey .Values.api "env" }}
              {{- range $env := .Values.api.env }}
            - name: {{ $env.name | quote }}
              value: {{- if and (eq (typeOf $env.value) "bool") }} {{ $env.value }} {{- else }} {{ $env.value | quote }} {{- end }}
              {{- end}}
            {{- end }}
          image: '{{ .Values.api.repository }}:{{ .Values.api.tag }}'
          {{- if hasKey .Values.api "resources" }}
          resources:
          {{- if hasKey .Values.api.resources "limits" }}
          limits:
            memory: {{ .Values.api.resources.limits.memory | quote }}
            cpu: {{ .Values.api.resources.limits.cpu | quote }}
          {{- end }}
          {{- if hasKey .Values.api.resources "requests" }}
          requests:
            memory: {{ .Values.api.resources.requests.memory | quote }}
            cpu: {{ .Values.api.resources.requests.cpu | quote }}
          {{- end }}
          {{- end }}
          ports:
          - containerPort: {{ .Values.api.port }}
          name: {{ .Values.api.name }}
      restartPolicy: Always
      {{- if hasKey .Values.api "imagePullSecrets" }}
      imagePullSecrets:
        {{- range .Values.api.imagePullSecrets }}
      - name: {{ . }}
        {{- end }}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ print .Release.Name "-compreface-api" | lower | nospace }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
      app: {{ print .Release.Name "-api" }}
  ports:
  - port: {{ .Values.api.port }}
