apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ print .Release.Name "-api" }}
  name: {{ print .Release.Name "-" .Values.api.name | lower | nospace }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: {{ print .Release.Name "-api" }}
  template:
    metadata:
      labels:
        app: {{ print .Release.Name "-api" }}
    spec:
      containers:
        - env:
            - name: API_JAVA_OPTS
              value: '-Xmx8g'
            - name: POSTGRES_PASSWORD
              value: '{{ .Values.postgres.db_password }}'
            - name: POSTGRES_URL
              value: 'jdbc:postgresql://compreface-postgres-db:{{ .Values.postgres.db_port }}/{{ .Values.postgres.db_name }}'
            - name: POSTGRES_USER
              value: '{{ .Values.postgres.db_user }}'
            - name: SAVE_IMAGES_TO_DB
              value: 'true'
            - name: SPRING_PROFILES_ACTIVE
              value: 'dev'
          image: '{{ .Values.api.repository }}:{{ .Values.api.tag }}'
          resources:
          {{- if .Values.api.resources.limits }}
          limits:
            memory: {{ default "256Mi" .Values.api.resources.limits.memory | quote }}
            cpu: {{ default "0.02" .Values.api.resources.limits.cpu | quote }}
          {{- end }}
          {{- if .Values.api.resources.requests }}
          requests:
            memory: {{ default "125Mi" .Values.api.resources.requests.memory | quote }}
            cpu: {{ default "0.015" .Values.api.resources.requests.cpu | quote }}
          {{- end }}
          ports:
          - containerPort: {{ .Values.api.port }}
          name: {{ .Values.api.name }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: {{ print .Release.Name "-compreface-api" | lower | nospace }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
      app: {{ print .Release.Name "-api" }}
  ports:
  - port: {{ .Values.api.port }}
