apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ print .Release.Name "-fe" }}
  name: {{ print .Release.Name "-" .Values.fe.name | lower | nospace }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.fe.replicas }}
  selector:
    matchLabels:
      app: {{ print .Release.Name "-fe" }}
  template:
    metadata:
      labels:
        app: {{ print .Release.Name "-fe" }}
    spec:
      containers:
        - env:
            - name: CLIENT_MAX_BODY_SIZE
              value: {{ default "5000K".Values.fe.maxBodySize }}
        - image: '{{ .Values.fe.repository }}:{{ .Values.fe.tag }}'
          resources:
          {{- if .Values.fe.resources.limits }}
          limits:
            memory: {{ default "256Mi" .Values.fe.resources.limits.memory | quote }}
            cpu: {{ default "0.02" .Values.fe.resources.limits.cpu | quote }}
          {{- end }}
          {{- if .Values.fe.resources.requests }}
          requests:
            memory: {{ default "125Mi" .Values.fe.resources.requests.memory | quote }}
            cpu: {{ default "0.015" .Values.fe.resources.requests.cpu | quote }}
          {{- end }}
          name: {{ .Values.fe.name }}
          ports:
            - containerPort: {{ .Values.fe.port }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ print .Release.Name "-fe" }}
  name: {{ print .Release.Name "-compreface-ui" | lower | nospace }}
  namespace: {{ .Release.Namespace }}
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: {{ .Values.fe.port }}
  selector:
    app: {{ print .Release.Name "-fe" }}
---
{{- if and (hasKey .Values.fe "ingress") (hasKey .Values.fe.ingress "enabled") .Values.fe.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
{{- with .Values.fe.ingress.annotations }}
  {{- range $key, $value := . }}
    {{ $key }}: {{- if and (eq (typeOf $value) "bool") }} {{ $value }} {{- else }} {{ $value | quote }} {{- end }}
  {{- end }}
{{- end }}
  name: {{ print .Release.Name "-" .Values.fe.name | lower | nospace }}
  namespace: {{ .Release.Namespace }}
spec:
{{- if hasKey .Values.fe.ingress "className" }}
  ingressClassName: {{ .Values.fe.ingress.className }}
{{- end }}
{{- if .Values.fe.ingress.tls }}
  tls:
    - hosts:
  {{- with .Values.fe.ingress.hosts }}
    {{- range . }}
        - {{ . | lower | nospace }}
    {{- end }}
  {{- end }}
      secretName: {{ print .Values.fe.name "-ingress" | lower | nospace }}
{{- end }}
  rules:
{{- range .Values.fe.ingress.hosts }}
  - host: {{ . | lower | nospace }}
    http:
      paths:
      - backend:
          service:
            name: compreface-ui
            port:
              number: 8000
        path: /
        pathType: Prefix
{{- end }}
{{- end }}

